version: '3.0'
services:
  mongo:
    image: mongo:5.0.7
    ports:
      - "27017:27017"
    volumes:
      - ./docker-compose-files/mongo:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: niong-commerce
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      discovery.type: single-node
  serve:
    image: node:17.9.0
    depends_on:
      - mongo
#      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    working_dir: /app
    command: bash -c "npm i -g pnpm @nestjs/cli && pnpm i && pnpm start"
    environment:
      NODE_ENV: local_docker
